### ISSUE TITLE
Dreamscape doesn't work

### ISSUE THREAD

**Issue by GeoffreyRockwell** [sgsinclair/Voyant#503]
Dreamscape doesn’t seem to be working in certain situations. If I try to use it on the Frankenstein text (https://voyant-tools.org/?corpus=frank&view=dreamscape) I get a "Failed to load location information" error.  If I go to https://voyant-tools.org/?view=dreamscape and then open a text like Austen, then it seems to work.

**Comment by ajmacdonald** [comment]
Note to self: seems to be a serialization/caching issue.

Error message:
```
org.voyanttools.trombone.model.Confidence; local class incompatible: stream classdesc serialVersionUID = -3441387218096079426, local class serialVersionUID = -6306687072362623335
java.io.InvalidClassException: org.voyanttools.trombone.model.Confidence; local class incompatible: stream classdesc serialVersionUID = -3441387218096079426, local class serialVersionUID = -6306687072362623335
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:687)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1875)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1744)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2032)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1965)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1560)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2277)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2201)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:426)
	at java.util.ArrayList.readObject(ArrayList.java:797)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2168)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2059)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1566)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:426)
	at org.voyanttools.trombone.storage.file.FileStorage.retrieve(FileStorage.java:314)
	at org.voyanttools.trombone.tool.corpus.DocumentLocationTokens.getLocationTokens(DocumentLocationTokens.java:102)
	at org.voyanttools.trombone.tool.corpus.Dreamscape.run(Dreamscape.java:83)
```

**Comment by sorchadubh** [comment]
Any progress on a fix? would really like to use this tool!

**Comment by ajmacdonald** [comment]
Hello @sorchadubh 
I hope this will be fixed the next time I do a major update of the site.
In the meantime, you can use the tool on the beta site: https://beta.voyant-tools.org/

**Comment by sorchadubh** [comment]
Super!

thanks very much for this: I will let you know how it goes.

Sue
